export const wheelchairs = [
  {
    slug: "x1-lite",
    name: "Xiaoxiang X1 Lite",
    tagline: "Lightweight & Compact Folding Electric Wheelchair",
    category: "wheelchair",
    brand: "Xiaoxiang Wheelchair",
    description:
      "The X1 Lite is our most portable electric wheelchair, designed for users who need mobility on the go. At just 19kg, it folds compactly for car trunks and airplane travel. Despite its light weight, it delivers a reliable 20km range on a single charge.",
    specs: [
      { label: "Weight", value: "19 kg (41.9 lbs)" },
      { label: "Max Load", value: "120 kg (265 lbs)" },
      { label: "Range", value: "20 km (12.4 mi)" },
      { label: "Max Speed", value: "6 km/h (3.7 mph)" },
      { label: "Battery", value: "24V / 10Ah Lithium-ion" },
      { label: "Motor", value: "250W x 2 Brushless" },
      { label: "Folding", value: "Yes — compact fold" },
      { label: "Charging Time", value: "4–5 hours" },
    ],
    features: [
      "Ultra-light 19kg frame — easy to lift and carry",
      "Quick-fold mechanism collapses in seconds",
      "Smart joystick controller with speed adjustment",
      "Anti-tip wheels for safety on inclines",
      "Puncture-proof solid tires — no maintenance",
    ],
    image: "/images/wheelchair-x1.jpg",
    bgColor: "bg-amber-50",
    accentColor: "text-orange-500",
    accentBg: "bg-orange-500",
  },
  {
    slug: "x2-comfort",
    name: "Xiaoxiang X2 Comfort",
    tagline: "Ergonomic Comfort with Extended Range — Our Bestseller",
    category: "wheelchair",
    brand: "Xiaoxiang Wheelchair",
    description:
      "The X2 Comfort strikes the perfect balance between comfort, range, and value. Our best-selling model features an ergonomic seat with adjustable armrests and a 25km range. It's the ideal choice for daily use, whether at home, in the community, or at work.",
    specs: [
      { label: "Weight", value: "26 kg (57.3 lbs)" },
      { label: "Max Load", value: "130 kg (287 lbs)" },
      { label: "Range", value: "25 km (15.5 mi)" },
      { label: "Max Speed", value: "8 km/h (5 mph)" },
      { label: "Battery", value: "24V / 15Ah Lithium-ion" },
      { label: "Motor", value: "300W x 2 Brushless" },
      { label: "Folding", value: "Yes — quick-release" },
      { label: "Charging Time", value: "5–6 hours" },
    ],
    features: [
      "Ergonomic high-back seat with breathable mesh",
      "Adjustable armrests and footplates",
      "Dual 300W motors for smooth hill climbing",
      "Digital display with speed, distance & battery",
      "LED headlight and reflectors for night safety",
    ],
    image: "/images/wheelchair-x2.jpg",
    bgColor: "bg-sky-50",
    accentColor: "text-sky-500",
    accentBg: "bg-sky-500",
  },
  {
    slug: "x3-pro",
    name: "Xiaoxiang X3 Pro",
    tagline: "Premium Smart Electric Wheelchair with 40km Range",
    category: "wheelchair",
    brand: "Xiaoxiang Wheelchair",
    description:
      "The X3 Pro is our flagship model, combining cutting-edge smart controls with a powerful battery system for an industry-leading 40km range. Designed for users who demand the very best, it features app connectivity, voice control, and advanced safety systems.",
    specs: [
      { label: "Weight", value: "32 kg (70.5 lbs)" },
      { label: "Max Load", value: "150 kg (331 lbs)" },
      { label: "Range", value: "40 km (24.9 mi)" },
      { label: "Max Speed", value: "10 km/h (6.2 mph)" },
      { label: "Battery", value: "48V / 20Ah Lithium-ion" },
      { label: "Motor", value: "400W x 2 Brushless" },
      { label: "Folding", value: "Yes — power-assist fold" },
      { label: "Charging Time", value: "6–7 hours" },
    ],
    features: [
      "Smartphone app control — drive, lock & monitor remotely",
      "Voice command support (English & Chinese)",
      "40km ultra-long range for all-day use",
      "All-terrain tires — indoor & outdoor capable",
      "360° obstacle detection with automatic braking",
    ],
    image: "/images/wheelchair-x3.jpg",
    bgColor: "bg-rose-50",
    accentColor: "text-rose-400",
    accentBg: "bg-rose-400",
  },
];

export const motors = [
  {
    slug: "dpg-80-series",
    name: "DPG-80 Series",
    tagline: "General Purpose Industrial Motors — 0.75 to 2.2kW",
    category: "motor",
    brand: "Dongbang Motor (DPG)",
    description:
      "The DPG-80 Series is our entry-level industrial motor line, offering reliable performance for general-purpose applications. With power ratings from 0.75kW to 2.2kW, these motors are ideal for pumps, fans, compressors, and light conveyor systems. Built with precision-wound copper windings and sealed ball bearings for long service life.",
    specs: [
      { label: "Power Range", value: "0.75 – 2.2 kW (1 – 3 HP)" },
      { label: "Voltage", value: "220V / 380V / 440V (50/60Hz)" },
      { label: "Frame Size", value: "IEC 80 (80–90L)" },
      { label: "Efficiency Class", value: "IE3 (Premium Efficiency)" },
      { label: "Protection", value: "IP55 — Dust & water-jet resistant" },
      { label: "Insulation Class", value: "F (155°C)" },
      { label: "Mounting", value: "B3 / B5 / B14 foot & flange" },
      { label: "Certification", value: "CE, CCC, ISO 9001" },
    ],
    features: [
      "High-efficiency IE3 design — energy saving",
      "Low-vibration, low-noise operation",
      "Double-shielded ball bearings for long life",
      "Die-cast aluminum frame for lightweight strength",
      "Suitable for inverter / VFD operation",
    ],
    image: "/images/motor-dpg80.jpg",
    bgColor: "bg-gray-100",
    accentColor: "text-blue-600",
    accentBg: "bg-blue-600",
  },
  {
    slug: "dpg-100-series",
    name: "DPG-100 Series",
    tagline: "High-Efficiency Motors — 3 to 7.5kW for Industrial Duty",
    category: "motor",
    brand: "Dongbang Motor (DPG)",
    description:
      "The DPG-100 Series delivers high efficiency and robust construction for demanding industrial applications. With outputs from 3kW to 7.5kW, these motors excel in material handling, machining, HVAC, and agricultural machinery. Featuring optimized electromagnetic design and premium-grade materials.",
    specs: [
      { label: "Power Range", value: "3.0 – 7.5 kW (4 – 10 HP)" },
      { label: "Voltage", value: "380V / 660V (50/60Hz)" },
      { label: "Frame Size", value: "IEC 100 (100–132M)" },
      { label: "Efficiency Class", value: "IE4 (Super Premium)" },
      { label: "Protection", value: "IP55 — Dust & water-jet resistant" },
      { label: "Insulation Class", value: "F (155°C) / H (180°C) optional" },
      { label: "Mounting", value: "B3 / B5 / B35 foot & flange" },
      { label: "Certification", value: "CE, CCC, UL, ISO 9001" },
    ],
    features: [
      "IE4 super-premium efficiency — lowest operating costs",
      "Class F insulation with Class B temperature rise",
      "Cast iron frame for superior vibration damping",
      "Sealed regreasable bearings for extended service",
      "Optional encoder-ready and brake variants",
    ],
    image: "/images/motor-dpg100.jpg",
    bgColor: "bg-gray-100",
    accentColor: "text-blue-700",
    accentBg: "bg-blue-700",
  },
  {
    slug: "dpg-150-series",
    name: "DPG-150 Series",
    tagline: "Heavy Duty Industrial Motors — 11 to 22kW",
    category: "motor",
    brand: "Dongbang Motor (DPG)",
    description:
      "The DPG-150 Series is our heavy-duty workhorse, engineered for the toughest industrial environments. From 11kW to 22kW, these motors power large pumps, crushers, extruders, hoists, and industrial fans. Built with a rugged cast-iron housing, reinforced bearings, and advanced cooling systems for 24/7 continuous operation.",
    specs: [
      { label: "Power Range", value: "11 – 22 kW (15 – 30 HP)" },
      { label: "Voltage", value: "380V / 660V / 690V (50/60Hz)" },
      { label: "Frame Size", value: "IEC 150 (160L–180L)" },
      { label: "Efficiency Class", value: "IE4 (Super Premium)" },
      { label: "Protection", value: "IP55 / IP56 / IP65 options" },
      { label: "Insulation Class", value: "H (180°C) standard" },
      { label: "Mounting", value: "B3 / B35 / V1 foot & flange" },
      { label: "Certification", value: "CE, CCC, UL, ATEX (optional)" },
    ],
    features: [
      "IE4 super-premium efficiency — heavy-duty rated",
      "Cast-iron housing with external ribbed cooling",
      "Reinforced bearing system for high radial loads",
      "Optional ATEX certification for explosive environments",
      "Built-in thermal protection (PTC thermistor)",
    ],
    image: "/images/motor-dpg150.jpg",
    bgColor: "bg-gray-100",
    accentColor: "text-blue-800",
    accentBg: "bg-blue-800",
  },
];

export const allProducts = [...wheelchairs, ...motors];

export function getProductBySlug(slug) {
  return allProducts.find((p) => p.slug === slug) || null;
}
