export const wheelchairs = [
  {
    slug: "miniredone-i",
    name: "MiniRedone-I",
    fullName: "MiniElephant MiniRedone-I",
    tagline: "The reliable workhorse : base folding electric wheelchair",
    description:
      "The MiniRedone-I is a factory-direct folding electric wheelchair built on an aerospace-grade one-piece magnesium alloy die-cast frame — because the frame is cast as a single unit with zero welds or joints, it delivers superior structural strength while keeping the total weight at just 47KG. That lightweight magnesium alloy construction means a caregiver can fold and lift the electric wheelchair into a car trunk unaided — a decisive advantage for seniors living in walk-up apartments, home-care nurses making daily visits, and families who travel with their mobility equipment. Dual 350W self-developed hub motors with planetary gear structure deliver 85% energy efficiency and whisper-quiet operation, so the user can glide smoothly indoors and outdoors on a single 16Ah LiFePO₄ battery charge covering up to 30km. Certified ISO 13485, CE, and FDA for B2B export, with OEM/ODM customization available.",
    specs: [
      { label: "Net Weight", value: "47 KG" },
      { label: "Max Load", value: "150 KG" },
      { label: "Range", value: "≈30 KM" },
      { label: "Max Speed", value: "≤6 KM/H" },
      { label: "Battery", value: "16Ah LiFePO₄ Lithium Battery" },
      { label: "Motor", value: "Dual 350W Self-developed Hub Motors" },
      { label: "Frame Material", value: "Magnesium Alloy (one-piece die-cast)" },
      { label: "Folded Dimensions", value: "L850×W675×H780 mm" },
      { label: "Seat Dimensions", value: "L1080×W675×H1020 mm" },
      { label: "Tires", value: "Black pneumatic tires" },
      { label: "Charging Time", value: "4-6 hours" },
    ],
    features: [
      "One-piece magnesium alloy die-cast frame — no welding, superior strength",
      "Dual 350W self-developed hub motors : whisper-quiet, 85% efficiency",
      "Zero rolling resistance when free-wheeling — easy to push without power",
      "16Ah LiFePO₄ battery : 30km range, 2000+ charge cycles, superior safety",
      "Modular seat system : swap between sofa-style, comfort, or elegant wooden seats",
      "Pneumatic shock-absorbing front fork with gas spring for smooth ride",
      "Hand/foot dual brake system for convenient operation",
      "Anti-tip wheels : tested for 15° slope safety",
      "Foldable design for easy storage and transport",
    ],
    keyDifference: "Base model, black tires",
    category: "MiniRedone Series",
        images: ['/images/miniredone-i.webp', '/images/miniredone-i-1.webp', '/images/miniredone-i-2.webp', '/images/miniredone-i-3.webp'],
    colorVariant: false,
  },
  {
    slug: "miniredone-i-w",
    name: "MiniRedone-I-W",
    fullName: "MiniElephant MiniRedone-I-W",
    tagline: "White edition : clean, modern, and stylish",
    description:
      "The MiniRedone-I-W is the white color variant of our classic I-series wheelchair. Featuring the same one-piece magnesium alloy die-cast frame, self-developed hub motors, and LiFePO₄ battery, this model stands out with its clean white finish that appeals to users looking for a modern aesthetic. Perfect for healthcare facilities and modern homes.",
    specs: [
      { label: "Net Weight", value: "46 KG" },
      { label: "Max Load", value: "150 KG" },
      { label: "Range", value: "≈30 KM" },
      { label: "Max Speed", value: "≤6 KM/H" },
      { label: "Battery", value: "16Ah LiFePO₄ Lithium Battery" },
      { label: "Motor", value: "Dual 350W Self-developed Hub Motors" },
      { label: "Frame Material", value: "Magnesium Alloy (one-piece die-cast)" },
      { label: "Folded Dimensions", value: "L830×W675×H780 mm" },
      { label: "Seat Dimensions", value: "L1005×W675×H1020 mm" },
      { label: "Color", value: "White" },
      { label: "Charging Time", value: "4-6 hours" },
    ],
    features: [
      "Clean white finish : modern aesthetic for healthcare and home",
      "One-piece magnesium alloy die-cast frame — no welding, superior strength",
      "Dual 350W self-developed hub motors : whisper-quiet operation",
      "16Ah LiFePO₄ battery : 30km range, 2000+ charge cycles",
      "Modular seat system compatible with multiple seat styles",
      "Pneumatic shock-absorbing front fork with gas spring",
      "Hand/foot dual brake system",
      "Foldable design for easy storage",
      "Compact folded dimensions: L830×W675×H780 mm",
      "Anti-tip wheels tested for 15° slope safety",
    ],
    keyDifference: "White variant, slightly lighter at 46KG",
    category: "MiniRedone Series",
        images: ['/images/miniredone-i-w.webp', '/images/miniredone-i-w-1.webp', '/images/miniredone-i-w-2.webp', '/images/miniredone-i-w-3.webp'],
    colorVariant: true,
  },
  {
    slug: "miniredone-i-br",
    name: "MiniRedone-I-B&R",
    fullName: "MiniElephant MiniRedone-I-B&R",
    tagline: "Available in Black & Red or Black & Orange",
    description:
      "The MiniRedone-I-B&R offers vibrant color options to suit personal preference. Choose between the bold Black & Red or the energetic Black & Orange combination. Built on the same one-piece magnesium alloy die-cast frame with self-developed hub motors and LiFePO₄ battery, it delivers the full MiniRedone performance with a personalized touch.",
    specs: [
      { label: "Net Weight", value: "46 KG" },
      { label: "Max Load", value: "150 KG" },
      { label: "Range", value: "≈30 KM" },
      { label: "Max Speed", value: "≤6 KM/H" },
      { label: "Battery", value: "16Ah LiFePO₄ Lithium Battery" },
      { label: "Motor", value: "Dual 350W Self-developed Hub Motors" },
      { label: "Frame Material", value: "Magnesium Alloy (one-piece die-cast)" },
      { label: "Folded Dimensions", value: "L830×W675×H780 mm" },
      { label: "Seat Dimensions", value: "L1005×W675×H1020 mm" },
      { label: "Color Options", value: "Black & Red / Black & Orange" },
      { label: "Charging Time", value: "4-6 hours" },
    ],
    features: [
      "Choice of Black & Red or Black & Orange color schemes",
      "One-piece magnesium alloy die-cast frame — no welding, superior strength",
      "Dual 350W self-developed hub motors : whisper-quiet, 85% efficiency",
      "16Ah LiFePO₄ battery : 30km range, 2000+ charge cycles",
      "Modular seat system compatible with multiple seat styles",
      "Pneumatic shock-absorbing front fork with gas spring",
      "Hand/foot dual brake system",
      "Foldable compact design",
      "Anti-tip wheels for enhanced safety",
    ],
    keyDifference: "Red/Orange color options",
    category: "MiniRedone Series",
        images: ['/images/miniredone-i-br.webp', '/images/miniredone-i-br-1.webp', '/images/miniredone-i-br-2.webp', '/images/miniredone-i-br-3.webp'],
    colorVariant: true,
  },
  {
    slug: "miniredone-i-r",
    name: "MiniRedone-I-R",
    fullName: "MiniElephant MiniRedone-I-R",
    tagline: "Red edition : bold, vibrant, and full of energy",
    description:
      "The MiniRedone-I-R is our striking Red Edition wheelchair. With its vibrant red accents and sleek black frame, this model makes a bold statement while delivering the same one-piece magnesium alloy die-cast frame, self-developed hub motors, and LiFePO₄ battery technology that defines the MiniRedone series.",
    specs: [
      { label: "Net Weight", value: "46 KG" },
      { label: "Max Load", value: "150 KG" },
      { label: "Range", value: "≈30 KM" },
      { label: "Max Speed", value: "≤6 KM/H" },
      { label: "Battery", value: "16Ah LiFePO₄ Lithium Battery" },
      { label: "Motor", value: "Dual 350W Self-developed Hub Motors" },
      { label: "Frame Material", value: "Magnesium Alloy (one-piece die-cast)" },
      { label: "Folded Dimensions", value: "L830×W675×H780 mm" },
      { label: "Seat Dimensions", value: "L1005×W675×H1020 mm" },
      { label: "Color", value: "Red Edition" },
      { label: "Charging Time", value: "4-6 hours" },
    ],
    features: [
      "Bold Red Edition design with vibrant red accents",
      "One-piece magnesium alloy die-cast frame — no welding, superior strength",
      "Dual 350W self-developed hub motors : whisper-quiet, zero push resistance",
      "16Ah LiFePO₄ battery : 30km range, 2000+ charge cycles",
      "Modular seat system compatible with multiple seat styles",
      "Pneumatic shock-absorbing front fork with gas spring",
      "Hand/foot dual brake system",
      "Foldable frame for convenient storage",
      "Anti-tip wheels tested for 15° slope safety",
    ],
    keyDifference: "Red edition",
    category: "MiniRedone Series",
        images: ['/images/miniredone-i-r.webp', '/images/miniredone-i-r-1.webp', '/images/miniredone-i-r-2.webp', '/images/miniredone-i-r-3.webp'],
    colorVariant: true,
  },
  {
    slug: "miniredone-i-plus",
    name: "MiniRedone-I-Plus",
    fullName: "MiniElephant MiniRedone-I-Plus",
    tagline: "Upgraded base model with enhanced comfort",
    description:
      "The MiniRedone-I-Plus takes everything you love about the standard I-series and elevates it with enhanced comfort features and upgraded components. Built on the same one-piece magnesium alloy die-cast frame with self-developed hub motors, it adds improved padding, upgraded controller, and refined ergonomics for a noticeably better riding experience.",
    specs: [
      { label: "Net Weight", value: "~47 KG" },
      { label: "Max Load", value: "150 KG" },
      { label: "Range", value: "≈30 KM" },
      { label: "Max Speed", value: "≤6 KM/H" },
      { label: "Battery", value: "16Ah LiFePO₄ Lithium Battery" },
      { label: "Motor", value: "Dual 350W Self-developed Hub Motors" },
      { label: "Frame Material", value: "Magnesium Alloy (one-piece die-cast)" },
      { label: "Folded Dimensions", value: "L850×W675×H780 mm" },
      { label: "Seat Dimensions", value: "L1080×W675×H1020 mm" },
      { label: "Charging Time", value: "4-6 hours" },
    ],
    features: [
      "Upgraded memory foam seat cushion for extended comfort",
      "Enhanced joystick controller with smoother response",
      "One-piece magnesium alloy die-cast frame — no welding, superior strength",
      "Dual 350W self-developed hub motors : whisper-quiet, 85% efficiency",
      "16Ah LiFePO₄ battery : 30km range, 2000+ charge cycles",
      "Modular seat system compatible with multiple seat styles",
      "Pneumatic shock-absorbing front fork with gas spring",
      "Hand/foot dual brake system",
      "Quick-release folding mechanism",
      "Anti-tip wheels tested for 15° slope safety",
    ],
    keyDifference: "Upgraded base model with enhanced comfort features",
    category: "MiniRedone Series",
        images: ['/images/miniredone-i.webp', '/images/miniredone-i-1.webp', '/images/miniredone-i-2.webp', '/images/miniredone-i-3.webp'],
    colorVariant: false,
  },
  {
    slug: "miniredone-ii",
    name: "MiniRedone-II",
    fullName: "MiniElephant MiniRedone-II",
    tagline: "Lighter design at just 42KG : ultimate portability",
    description:
      "The MiniRedone-II is the lightweight champion of our electric wheelchair line at just 42KG — because every structural component is engineered around a one-piece magnesium alloy die-cast frame with no welding joints, we eliminated excess weight without sacrificing the 150KG load capacity. This featherweight folding electric wheelchair is designed for frequent travelers, apartment dwellers without elevators, and users who need to load and unload their mobility aid multiple times per day: the frame folds compactly in seconds, fits easily into car trunks, and can be carried up a single flight of stairs by one adult. Powered by dual 350W self-developed hub motors (85% energy efficiency) and a 16Ah LiFePO₄ battery with 2000+ charge cycles, it delivers a 30km range on one charge. ISO 13485, CE, and FDA certified for international B2B export.",
    specs: [
      { label: "Net Weight", value: "42 KG" },
      { label: "Max Load", value: "150 KG" },
      { label: "Range", value: "≈30 KM" },
      { label: "Max Speed", value: "≤6 KM/H" },
      { label: "Battery", value: "16Ah LiFePO₄ Lithium Battery" },
      { label: "Motor", value: "Dual 350W Self-developed Hub Motors" },
      { label: "Frame Material", value: "Magnesium Alloy (one-piece die-cast)" },
      { label: "Folded Dimensions", value: "L830×W675×H945 mm" },
      { label: "Seat Dimensions", value: "L1005×W675×H945 mm" },
      { label: "Charging Time", value: "4-6 hours" },
    ],
    features: [
      "Ultra-light 42KG frame : easiest to lift and transport",
      "One-piece magnesium alloy die-cast frame — no welding, superior strength",
      "Dual 350W self-developed hub motors : whisper-quiet, 85% efficiency",
      "Zero rolling resistance when free-wheeling — easy to push without power",
      "16Ah LiFePO₄ battery : 30km range, 2000+ charge cycles",
      "Modular seat system compatible with multiple seat styles",
      "Pneumatic shock-absorbing front fork with gas spring",
      "Hand/foot dual brake system",
      "Compact folding design",
      "Anti-tip wheels tested for 15° slope safety",
    ],
    keyDifference: "Lighter weight at 42KG",
    category: "MiniRedone Series",
        images: ['/images/miniredone-ii.webp', '/images/miniredone-ii-1.webp', '/images/miniredone-ii-2.webp'],
    colorVariant: false,
  },
  {
    slug: "miniredone-ii-plus",
    name: "MiniRedone-II-Plus",
    fullName: "MiniElephant MiniRedone-II-Plus",
    tagline: "Lightweight with a wider 750mm seat for extra comfort",
    description:
      "The MiniRedone-II-Plus combines the lightweight design of the II-series with a wider W750mm seat, offering enhanced comfort for larger users. Built on the same one-piece magnesium alloy die-cast frame with self-developed hub motors and LiFePO₄ battery, at just 45KG it remains highly portable while providing the extra space needed for all-day comfort.",
    specs: [
      { label: "Net Weight", value: "45 KG" },
      { label: "Max Load", value: "150 KG" },
      { label: "Range", value: "≈30 KM" },
      { label: "Max Speed", value: "≤6 KM/H" },
      { label: "Battery", value: "16Ah LiFePO₄ Lithium Battery" },
      { label: "Motor", value: "Dual 350W Self-developed Hub Motors" },
      { label: "Frame Material", value: "Magnesium Alloy (one-piece die-cast)" },
      { label: "Folded Dimensions", value: "L830×W675×H930 mm" },
      { label: "Seat Dimensions", value: "L1005×W750×H930 mm" },
      { label: "Charging Time", value: "4-6 hours" },
    ],
    features: [
      "Extra-wide W750mm seat for superior comfort",
      "Lightweight 45KG frame",
      "One-piece magnesium alloy die-cast frame — no welding, superior strength",
      "Dual 350W self-developed hub motors : whisper-quiet, 85% efficiency",
      "Zero rolling resistance when free-wheeling — easy to push without power",
      "16Ah LiFePO₄ battery : 30km range, 2000+ charge cycles",
      "Modular seat system compatible with multiple seat styles",
      "Pneumatic shock-absorbing front fork with gas spring",
      "Hand/foot dual brake system",
      "Foldable for easy transport",
      "Anti-tip wheels tested for 15° slope safety",
    ],
    keyDifference: "Wider seat (W750mm) at 45KG",
    category: "MiniRedone Series",
        images: ['/images/miniredone-ii-plus.webp', '/images/miniredone-ii-plus-1.webp', '/images/miniredone-ii-plus-3.webp', '/images/miniredone-ii-plus-4.webp'],
    colorVariant: false,
  },
  {
    slug: "miniredone-iii",
    name: "MiniRedone-III",
    fullName: "MiniElephant MiniRedone-III",
    tagline: "Premium high-back model : ultimate comfort and support",
    description:
      "The MiniRedone-III is the premium high-back electric wheelchair in the MiniRedone series — because its ergonomic high-back seat provides full upper-body support, users with weaker trunk control can sit comfortably for hours without fatigue or postural collapse. This makes it the preferred electric wheelchair for long-duration daily use, rehabilitation centers, and elderly users who need extra back support during extended outings. Built on the same one-piece magnesium alloy die-cast frame, it stays lightweight and foldable while supporting up to 150KG. The dual 350W self-developed hub motors with planetary gear structure provide 85% energy efficiency and a smooth, quiet ride, while the 16Ah LiFePO₄ battery delivers a 30km range. ISO 13485, CE, and FDA certified — ideal for B2B distributors and healthcare procurement.",
    specs: [
      { label: "Net Weight", value: "47 KG" },
      { label: "Max Load", value: "150 KG" },
      { label: "Range", value: "≈30 KM" },
      { label: "Max Speed", value: "≤6 KM/H" },
      { label: "Battery", value: "16Ah LiFePO₄ Lithium Battery" },
      { label: "Motor", value: "Dual 350W Self-developed Hub Motors" },
      { label: "Frame Material", value: "Magnesium Alloy (one-piece die-cast)" },
      { label: "Folded Dimensions", value: "L850×W675×H850 mm" },
      { label: "Seat Dimensions", value: "L1080×W675×H1200 mm" },
      { label: "Back Height", value: "High-back (1200mm)" },
      { label: "Charging Time", value: "4-6 hours" },
    ],
    features: [
      "Premium high-back design with 1200mm back height",
      "Memory foam seat and back cushion for superior comfort",
      "One-piece magnesium alloy die-cast frame — reinforced back support",
      "Dual 350W self-developed hub motors : whisper-quiet, 85% efficiency",
      "Zero rolling resistance when free-wheeling — easy to push without power",
      "16Ah LiFePO₄ battery : 30km range, 2000+ charge cycles",
      "Modular seat system compatible with multiple seat styles",
      "Pneumatic shock-absorbing front fork with gas spring",
      "Hand/foot dual brake system",
      "Reclining backrest option",
      "Adjustable headrest included",
      "Anti-tip wheels tested for 15° slope safety",
    ],
    keyDifference: "Premium/high back (1200mm seat height)",
    category: "MiniRedone Series",
        images: ['/images/miniredone-iii.webp', '/images/miniredone-iii-1.webp', '/images/miniredone-iii-2.webp', '/images/miniredone-iii-3.webp'],
    colorVariant: false,
  },
  {
    slug: "miniredone-iv",
    name: "MiniRedone-IV",
    fullName: "MiniElephant MiniRedone-IV",
    tagline: "Tall backrest design : 1250mm for full back support",
    description:
      "The MiniRedone-IV features the tallest backrest in the entire electric wheelchair series at 1250mm — because the extended backrest supports the full spinal column, it is the ideal electric wheelchair for users requiring complete postural alignment, including those with neuromuscular conditions or tall users who find standard backrests too short. The one-piece magnesium alloy die-cast frame keeps the total weight at just 43KG, so it remains fully foldable and portable despite its enhanced support structure. Dual 350W self-developed hub motors deliver 85% energy efficiency, and the 16Ah LiFePO₄ battery provides a 30km range with 2000+ charge cycles. ISO 13485, CE, and FDA certified for global B2B distribution and medical procurement channels.",
    specs: [
      { label: "Net Weight", value: "43 KG" },
      { label: "Max Load", value: "150 KG" },
      { label: "Range", value: "≈30 KM" },
      { label: "Max Speed", value: "≤6 KM/H" },
      { label: "Battery", value: "16Ah LiFePO₄ Lithium Battery" },
      { label: "Motor", value: "Dual 350W Self-developed Hub Motors" },
      { label: "Frame Material", value: "Magnesium Alloy (one-piece die-cast)" },
      { label: "Folded Dimensions", value: "L830×W675×H1250 mm" },
      { label: "Seat Dimensions", value: "L1005×W675×H1250 mm" },
      { label: "Back Height", value: "Extra tall (1250mm)" },
      { label: "Charging Time", value: "4-6 hours" },
    ],
    features: [
      "Extra tall 1250mm backrest for full back support",
      "Lightweight 43KG design",
      "One-piece magnesium alloy die-cast frame — no welding, superior strength",
      "Dual 350W self-developed hub motors : whisper-quiet, 85% efficiency",
      "Zero rolling resistance when free-wheeling — easy to push without power",
      "16Ah LiFePO₄ battery : 30km range, 2000+ charge cycles",
      "Modular seat system compatible with multiple seat styles",
      "Pneumatic shock-absorbing front fork with gas spring",
      "Hand/foot dual brake system",
      "Foldable with tall backrest",
      "Anti-tip wheels tested for 15° slope safety",
    ],
    keyDifference: "Tall backrest (1250mm) at 43KG",
    category: "MiniRedone Series",
        images: ['/images/miniredone-iv.webp', '/images/miniredone-iv-1.webp', '/images/miniredone-iv-2.webp', '/images/miniredone-iv-3.webp'],
    colorVariant: false,
  },
  {
    slug: "miniredone-v",
    name: "MiniRedone-V",
    fullName: "MiniElephant MiniRedone-V",
    tagline: "Wide-body extra comfort : 900mm width for spacious seating",
    description:
      "The MiniRedone-V is the extra-wide electric wheelchair with a spacious 900mm seat — because the expansive seat width accommodates larger users up to 150KG without the constriction of standard-width mobility aids, it provides all-day comfort for plus-size individuals and bariatric care applications. The reinforced one-piece magnesium alloy die-cast frame provides a stable, wide-base platform while keeping the electric wheelchair foldable for transport. Dual 350W self-developed hub motors with planetary gear structure deliver reliable, quiet propulsion with 85% energy efficiency, and the 16Ah LiFePO₄ battery offers a 30km range. ISO 13485, CE, and FDA certified — a strong addition to any B2B electric wheelchair product line targeting the bariatric and comfort segments.",
    specs: [
      { label: "Net Weight", value: "50 KG" },
      { label: "Max Load", value: "150 KG" },
      { label: "Range", value: "≈30 KM" },
      { label: "Max Speed", value: "≤6 KM/H" },
      { label: "Battery", value: "16Ah LiFePO₄ Lithium Battery" },
      { label: "Motor", value: "Dual 350W Self-developed Hub Motors" },
      { label: "Frame Material", value: "Magnesium Alloy (one-piece die-cast)" },
      { label: "Folded Dimensions", value: "L830×W900×H1200 mm" },
      { label: "Seat Dimensions", value: "L1005×W900×H1200 mm" },
      { label: "Seat Width", value: "Extra wide (900mm)" },
      { label: "Charging Time", value: "4-6 hours" },
    ],
    features: [
      "Extra wide 900mm seat : most spacious model",
      "50KG robust frame with reinforced construction",
      "Tall 1200mm backrest for full support",
      "One-piece magnesium alloy die-cast frame — wide-base stability",
      "Dual 350W self-developed hub motors : whisper-quiet, 85% efficiency",
      "Zero rolling resistance when free-wheeling — easy to push without power",
      "16Ah LiFePO₄ battery : 30km range, 2000+ charge cycles",
      "Modular seat system compatible with multiple seat styles",
      "Pneumatic shock-absorbing front fork with gas spring",
      "Hand/foot dual brake system",
      "Wide anti-tip wheels for enhanced stability",
      "Anti-tip wheels tested for 15° slope safety",
    ],
    keyDifference: "Wide/extra comfort (W900mm seat)",
    category: "MiniRedone Series",
        images: ['/images/miniredone-v.webp', '/images/miniredone-v-1.webp', '/images/miniredone-v-2.webp', '/images/miniredone-v-3.webp'],
    colorVariant: false,
  },
];

export const allProducts = [...wheelchairs];

export function getProductBySlug(slug) {
  return allProducts.find((p) => p.slug === slug) || null;
}
