export const wheelchairs = [
  {
    slug: "miniredone-i",
    name: "MiniRedone-I",
    fullName: "MiniElephant MiniRedone-I",
    tagline: "The reliable workhorse : base folding electric wheelchair",
    description:
      "MiniRedone-I is a factory-direct folding electric wheelchair built on a magnesium alloy frame platform. It is presented here as a B2B export model for distributors and OEM/ODM buyers.",
    b2bPrice: "1850.00",
    specs: [
      { label: "Net Weight", value: "47 KG" },
      { label: "Max Load", value: "150 KG" },
      { label: "Range", value: "≈30 KM" },
      { label: "Max Speed", value: "≤6 KM/H" },
      { label: "Battery", value: "16Ah LiFePO₄ Lithium Battery" },
      { label: "Motor", value: "Dual 350W Self-developed Hub Motors" },
      { label: "Frame Material", value: "Magnesium Alloy (one-piece die-cast)" },
      { label: "Folded Dimensions", value: "L850×W675×H780 mm" },
      { label: "Seat Dimensions", value: "L1080×W675×H1020 mm" },
      { label: "Tires", value: "Black pneumatic tires" },
      { label: "Charging Time", value: "4-6 hours" },
    ],
    features: [
      "One-piece magnesium alloy die-cast frame — no welding, superior strength",
      "Dual 350W self-developed hub motors : quiet brushless operation",
      "Manual maneuvering support is available when configured.",
      "rechargeable LiFePO₄ battery",
      "Modular seat system : swap between sofa-style, comfort, or elegant wooden seats",
      "Pneumatic shock-absorbing front fork with gas spring for smooth ride",
      "Hand/foot dual brake system for convenient operation",
      "anti-tip wheels for added stability",
      "Foldable design for easy storage and transport",
    ],
    keyDifference: "Base model, black tires",
    category: "MiniRedone Series",
    images: ["/images/miniredone-i.webp", "/images/miniredone-i-1.webp", "/images/miniredone-i-2.webp", "/images/miniredone-i-3.webp"],
    colorVariant: false,
  },
  {
    slug: "miniredone-i-w",
    name: "MiniRedone-I-W",
    fullName: "MiniElephant MiniRedone-I-W",
    tagline: "White edition : clean, modern, and stylish",
    description:
      "The MiniRedone-I-W is the elegant white edition of our premium electric wheelchair series — because the pristine white finish and refined design language appeal to discerning buyers and upscale healthcare environments, it brings a sense of calm, clinical-clean sophistication to daily mobility. Beneath its graceful exterior lies the same premium magnesium alloy one-piece magnesium alloy die-cast frame, dual 350W hub motors tuned for silent operation, and premium 16Ah LiFePO₄ battery. This is a high-end mobility solution for customers who value both aesthetics and engineering excellence.",
    b2bPrice: "1880.00",
    specs: [
      { label: "Net Weight", value: "46 KG" },
      { label: "Max Load", value: "150 KG" },
      { label: "Range", value: "≈30 KM" },
      { label: "Max Speed", value: "≤6 KM/H" },
      { label: "Battery", value: "16Ah LiFePO₄ Lithium Battery" },
      { label: "Motor", value: "Dual 350W Self-developed Hub Motors" },
      { label: "Frame Material", value: "Magnesium Alloy (one-piece die-cast)" },
      { label: "Folded Dimensions", value: "L830×W675×H780 mm" },
      { label: "Seat Dimensions", value: "L1005×W675×H1020 mm" },
      { label: "Color", value: "White" },
      { label: "Charging Time", value: "4-6 hours" },
    ],
    features: [
      "Clean white finish : modern aesthetic for healthcare and home",
      "One-piece magnesium alloy die-cast frame — no welding, superior strength",
      "Dual 350W self-developed hub motors : whisper-quiet operation",
      "16Ah LiFePO₄ battery",
      "Modular seat system compatible with multiple seat styles",
      "Pneumatic shock-absorbing front fork with gas spring",
      "Hand/foot dual brake system",
      "Foldable design for easy storage",
      "Compact folded dimensions: L830×W675×H780 mm",
      "Anti-tip wheels for added stability",
    ],
    keyDifference: "White variant, slightly lighter at 46KG",
    category: "MiniRedone Series",
    images: ["/images/miniredone-i-w.webp", "/images/miniredone-i-w-1.webp", "/images/miniredone-i-w-2.webp", "/images/miniredone-i-w-3.webp"],
    colorVariant: true,
  },
  {
    slug: "miniredone-i-br",
    name: "MiniRedone-I-B&R",
    fullName: "MiniElephant MiniRedone-I-B&R",
    tagline: "Available in Black & Red or Black & Orange",
    description:
      "The MiniRedone-I-B&R offers sophisticated dual-tone styling in Black & Red or Black & Orange — because the refined color combinations add a personal, expressive touch to premium mobility, it appeals to younger affluent users and design-conscious families who want a wheelchair that reflects their personality. The magnesium alloy die-cast frame, whisper-quiet dual 350W hub motors, and premium LiFePO₄ battery deliver the same high-end performance and comfort as the entire MiniRedone series.",
    b2bPrice: "1880.00",
    specs: [
      { label: "Net Weight", value: "46 KG" },
      { label: "Max Load", value: "150 KG" },
      { label: "Range", value: "≈30 KM" },
      { label: "Max Speed", value: "≤6 KM/H" },
      { label: "Battery", value: "16Ah LiFePO₄ Lithium Battery" },
      { label: "Motor", value: "Dual 350W Self-developed Hub Motors" },
      { label: "Frame Material", value: "Magnesium Alloy (one-piece die-cast)" },
      { label: "Folded Dimensions", value: "L830×W675×H780 mm" },
      { label: "Seat Dimensions", value: "L1005×W675×H1020 mm" },
      { label: "Color Options", value: "Black & Red / Black & Orange" },
      { label: "Charging Time", value: "4-6 hours" },
    ],
    features: [
      "Choice of Black & Red or Black & Orange color schemes",
      "One-piece magnesium alloy die-cast frame — no welding, superior strength",
      "Dual 350W self-developed hub motors : quiet brushless operation",
      "16Ah LiFePO₄ battery",
      "Modular seat system compatible with multiple seat styles",
      "Pneumatic shock-absorbing front fork with gas spring",
      "Hand/foot dual brake system",
      "Foldable compact design",
      "Anti-tip wheels for enhanced safety",
    ],
    keyDifference: "Red/Orange color options",
    category: "MiniRedone Series",
    images: ["/images/miniredone-i-br.webp", "/images/miniredone-i-br-1.webp", "/images/miniredone-i-br-2.webp", "/images/miniredone-i-br-3.webp"],
    colorVariant: true,
  },
  {
    slug: "miniredone-i-r",
    name: "MiniRedone-I-R",
    fullName: "MiniElephant MiniRedone-I-R",
    tagline: "Red edition : bold, vibrant, and full of energy",
    description:
      "The MiniRedone-I-R is the striking Red Edition of our premium electric wheelchair line — because the bold red accents against the sleek black frame create a confident, expressive look, it appeals to customers who want their mobility aid to reflect vitality and personality. Beyond the statement styling, it delivers the full luxury engineering of the MiniRedone series: magnesium alloy frame, silent dual 350W hub motors, and a premium LiFePO₄ battery — comfort and quality without compromise.",
    b2bPrice: "1880.00",
    specs: [
      { label: "Net Weight", value: "46 KG" },
      { label: "Max Load", value: "150 KG" },
      { label: "Range", value: "≈30 KM" },
      { label: "Max Speed", value: "≤6 KM/H" },
      { label: "Battery", value: "16Ah LiFePO₄ Lithium Battery" },
      { label: "Motor", value: "Dual 350W Self-developed Hub Motors" },
      { label: "Frame Material", value: "Magnesium Alloy (one-piece die-cast)" },
      { label: "Folded Dimensions", value: "L830×W675×H780 mm" },
      { label: "Seat Dimensions", value: "L1005×W675×H1020 mm" },
      { label: "Color", value: "Red Edition" },
      { label: "Charging Time", value: "4-6 hours" },
    ],
    features: [
      "Bold Red Edition design with vibrant red accents",
      "One-piece magnesium alloy die-cast frame — no welding, superior strength",
      "Dual 350W self-developed hub motors : whisper-quiet, zero push resistance",
      "16Ah LiFePO₄ battery",
      "Modular seat system compatible with multiple seat styles",
      "Pneumatic shock-absorbing front fork with gas spring",
      "Hand/foot dual brake system",
      "Foldable frame for convenient storage",
      "Anti-tip wheels for added stability",
    ],
    keyDifference: "Red edition",
    category: "MiniRedone Series",
    images: ["/images/miniredone-i-r.webp", "/images/miniredone-i-r-1.webp", "/images/miniredone-i-r-2.webp", "/images/miniredone-i-r-3.webp"],
    colorVariant: true,
  },
  {
    slug: "miniredone-i-plus",
    name: "MiniRedone-I-Plus",
    fullName: "MiniElephant MiniRedone-I-Plus",
    tagline: "Upgraded base model with enhanced comfort",
    description:
      "The MiniRedone-I-Plus elevates the premium I-series with enhanced comfort components and upgraded features — because every refinement is engineered around the rider's well-being, it delivers a noticeably more luxurious ride for users who spend extended time in their wheelchair. The upgraded ergonomic seating and refined suspension absorb road vibration for a plush, stable journey, while the magnesium alloy frame and dual 350W hub motors ensure effortless, silent propulsion. A premium choice for customers who demand the very best in daily comfort.",
    b2bPrice: "1920.00",
    specs: [
      { label: "Net Weight", value: "~47 KG" },
      { label: "Max Load", value: "150 KG" },
      { label: "Range", value: "≈30 KM" },
      { label: "Max Speed", value: "≤6 KM/H" },
      { label: "Battery", value: "16Ah LiFePO₄ Lithium Battery" },
      { label: "Motor", value: "Dual 350W Self-developed Hub Motors" },
      { label: "Frame Material", value: "Magnesium Alloy (one-piece die-cast)" },
      { label: "Folded Dimensions", value: "L850×W675×H780 mm" },
      { label: "Seat Dimensions", value: "L1080×W675×H1020 mm" },
      { label: "Charging Time", value: "4-6 hours" },
    ],
    features: [
      "Upgraded memory foam seat cushion for extended comfort",
      "Enhanced joystick controller with smoother response",
      "One-piece magnesium alloy die-cast frame — no welding, superior strength",
      "Dual 350W self-developed hub motors : quiet brushless operation",
      "16Ah LiFePO₄ battery",
      "Modular seat system compatible with multiple seat styles",
      "Pneumatic shock-absorbing front fork with gas spring",
      "Hand/foot dual brake system",
      "Quick-release folding mechanism",
      "Anti-tip wheels for added stability",
    ],
    keyDifference: "Upgraded base model with enhanced comfort features",
    category: "MiniRedone Series",
    images: ["/images/miniredone-i.webp", "/images/miniredone-i-1.webp", "/images/miniredone-i-2.webp", "/images/miniredone-i-3.webp"],
    colorVariant: false,
  },
  {
    slug: "miniredone-ii",
    name: "MiniRedone-II",
    fullName: "MiniElephant MiniRedone-II",
    tagline: "Lighter design at just 42KG : ultimate portability",
    description:
      "The MiniRedone-II is the lightweight flagship of our premium electric wheelchair line, designed for affluent users who want uncompromising comfort in an elegant, refined form. Because the entire frame is a one-piece magnesium alloy die-cast frame, it achieves a featherlight 42KG while retaining the strength of far heavier wheelchairs — an engineering achievement that translates directly into effortless indoor-outdoor transitions and a smoother, more controlled ride. Every detail speaks to quality: premium cushioned seating, dual 350W hub motors tuned for silent operation, and 16Ah LiFePO₄ battery with approximately 30km listed range. For the discerning buyer, the MiniRedone-II represents the perfect balance of high-end comfort and intelligent design.",
    b2bPrice: "1950.00",
    specs: [
      { label: "Net Weight", value: "42 KG" },
      { label: "Max Load", value: "150 KG" },
      { label: "Range", value: "≈30 KM" },
      { label: "Max Speed", value: "≤6 KM/H" },
      { label: "Battery", value: "16Ah LiFePO₄ Lithium Battery" },
      { label: "Motor", value: "Dual 350W Self-developed Hub Motors" },
      { label: "Frame Material", value: "Magnesium Alloy (one-piece die-cast)" },
      { label: "Folded Dimensions", value: "L830×W675×H945 mm" },
      { label: "Seat Dimensions", value: "L1005×W675×H945 mm" },
      { label: "Charging Time", value: "4-6 hours" },
    ],
    features: [
      "Ultra-light 42KG frame : easiest to lift and transport",
      "One-piece magnesium alloy die-cast frame — no welding, superior strength",
      "Dual 350W self-developed hub motors : quiet brushless operation",
      "Manual maneuvering support is available when configured.",
      "16Ah LiFePO₄ battery",
      "Modular seat system compatible with multiple seat styles",
      "Pneumatic shock-absorbing front fork with gas spring",
      "Hand/foot dual brake system",
      "Compact folding design",
      "Anti-tip wheels for added stability",
    ],
    keyDifference: "Lighter weight at 42KG",
    category: "MiniRedone Series",
    images: ["/images/miniredone-ii.webp", "/images/miniredone-ii-1.webp", "/images/miniredone-ii-2.webp"],
    colorVariant: false,
  },
  {
    slug: "miniredone-ii-plus",
    name: "MiniRedone-II-Plus",
    fullName: "MiniElephant MiniRedone-II-Plus",
    tagline: "Lightweight with a wider 750mm seat for extra comfort",
    description:
      "The MiniRedone-II-Plus combines the refined lightweight design of the II-series with a generous W750mm seat — because the extra width provides true premium comfort for larger users, it delivers first-class seating without the bulk of conventional power wheelchairs. The premium magnesium alloy one-piece magnesium alloy die-cast frame, silent dual 350W hub motors, and premium 16Ah LiFePO₄ battery come together in an elegant, high-end package that prioritizes both comfort and quality.",
    b2bPrice: "1980.00",
    specs: [
      { label: "Net Weight", value: "45 KG" },
      { label: "Max Load", value: "150 KG" },
      { label: "Range", value: "≈30 KM" },
      { label: "Max Speed", value: "≤6 KM/H" },
      { label: "Battery", value: "16Ah LiFePO₄ Lithium Battery" },
      { label: "Motor", value: "Dual 350W Self-developed Hub Motors" },
      { label: "Frame Material", value: "Magnesium Alloy (one-piece die-cast)" },
      { label: "Folded Dimensions", value: "L830×W675×H930 mm" },
      { label: "Seat Dimensions", value: "L1005×W750×H930 mm" },
      { label: "Charging Time", value: "4-6 hours" },
    ],
    features: [
      "Extra-wide W750mm seat for superior comfort",
      "Lightweight 45KG frame",
      "One-piece magnesium alloy die-cast frame — no welding, superior strength",
      "Dual 350W self-developed hub motors : quiet brushless operation",
      "Manual maneuvering support is available when configured.",
      "16Ah LiFePO₄ battery",
      "Modular seat system compatible with multiple seat styles",
      "Pneumatic shock-absorbing front fork with gas spring",
      "Hand/foot dual brake system",
      "Foldable for easy transport",
      "Anti-tip wheels for added stability",
    ],
    keyDifference: "Wider seat (W750mm) at 45KG",
    category: "MiniRedone Series",
    images: ["/images/miniredone-ii-plus.webp", "/images/miniredone-ii-plus-1.webp", "/images/miniredone-ii-plus-3.webp", "/images/miniredone-ii-plus-4.webp"],
    colorVariant: false,
  },
  {
    slug: "miniredone-iii",
    name: "MiniRedone-III",
    fullName: "MiniElephant MiniRedone-III",
    tagline: "Premium high-back model : ultimate comfort and support",
    description:
      "The MiniRedone-III is our most comfort-focused premium electric wheelchair, built for users who spend long hours seated and demand executive-level support. Because its ergonomic high-back seat cradles the full upper body, it dramatically reduces fatigue and postural strain during extended use — the kind of thoughtful comfort that distinguishes a premium mobility product from a basic medical device. The magnesium alloy die-cast frame provides a smooth, stable ride, while the dual 350W hub motors deliver silent, effortless propulsion. Combined with premium cushioning and a 16Ah LiFePO₄ battery, the MiniRedone-III offers a first-class mobility experience for those who see their wheelchair as an extension of their lifestyle.",
    b2bPrice: "1980.00",
    specs: [
      { label: "Net Weight", value: "47 KG" },
      { label: "Max Load", value: "150 KG" },
      { label: "Range", value: "≈30 KM" },
      { label: "Max Speed", value: "≤6 KM/H" },
      { label: "Battery", value: "16Ah LiFePO₄ Lithium Battery" },
      { label: "Motor", value: "Dual 350W Self-developed Hub Motors" },
      { label: "Frame Material", value: "Magnesium Alloy (one-piece die-cast)" },
      { label: "Folded Dimensions", value: "L850×W675×H850 mm" },
      { label: "Seat Dimensions", value: "L1080×W675×H1200 mm" },
      { label: "Back Height", value: "High-back (1200mm)" },
      { label: "Charging Time", value: "4-6 hours" },
    ],
    features: [
      "Premium high-back design with 1200mm back height",
      "Memory foam seat and back cushion for superior comfort",
      "One-piece magnesium alloy die-cast frame — reinforced back support",
      "Dual 350W self-developed hub motors : quiet brushless operation",
      "Manual maneuvering support is available when configured.",
      "16Ah LiFePO₄ battery",
      "Modular seat system compatible with multiple seat styles",
      "Pneumatic shock-absorbing front fork with gas spring",
      "Hand/foot dual brake system",
      "Reclining backrest option",
      "Adjustable headrest included",
      "Anti-tip wheels for added stability",
    ],
    keyDifference: "Premium/high back (1200mm seat height)",
    category: "MiniRedone Series",
    images: ["/images/miniredone-iii.webp", "/images/miniredone-iii-1.webp", "/images/miniredone-iii-2.webp", "/images/miniredone-iii-3.webp"],
    colorVariant: false,
  },
  {
    slug: "miniredone-iv",
    name: "MiniRedone-IV",
    fullName: "MiniElephant MiniRedone-IV",
    tagline: "Tall backrest design : 1250mm for full back support",
    description:
      "The MiniRedone-IV features the tallest backrest in the series at 1250mm — because the extended backrest provides complete spinal support, it is the premium choice for users who require full postural alignment and refuse to compromise on comfort. The premium magnesium alloy one-piece magnesium alloy die-cast frame keeps it refined and practical for transport, while the silent dual 350W hub motors and premium LiFePO₄ battery deliver a smooth, luxurious ride. Engineered for those who value quality, support, and dignity in every detail.",
    b2bPrice: "1950.00",
    specs: [
      { label: "Net Weight", value: "43 KG" },
      { label: "Max Load", value: "150 KG" },
      { label: "Range", value: "≈30 KM" },
      { label: "Max Speed", value: "≤6 KM/H" },
      { label: "Battery", value: "16Ah LiFePO₄ Lithium Battery" },
      { label: "Motor", value: "Dual 350W Self-developed Hub Motors" },
      { label: "Frame Material", value: "Magnesium Alloy (one-piece die-cast)" },
      { label: "Folded Dimensions", value: "L830×W675×H1250 mm" },
      { label: "Seat Dimensions", value: "L1005×W675×H1250 mm" },
      { label: "Back Height", value: "Extra tall (1250mm)" },
      { label: "Charging Time", value: "4-6 hours" },
    ],
    features: [
      "Extra tall 1250mm backrest for full back support",
      "Lightweight 43KG design",
      "One-piece magnesium alloy die-cast frame — no welding, superior strength",
      "Dual 350W self-developed hub motors : quiet brushless operation",
      "Manual maneuvering support is available when configured.",
      "16Ah LiFePO₄ battery",
      "Modular seat system compatible with multiple seat styles",
      "Pneumatic shock-absorbing front fork with gas spring",
      "Hand/foot dual brake system",
      "Foldable with tall backrest",
      "Anti-tip wheels for added stability",
    ],
    keyDifference: "Tall backrest (1250mm) at 43KG",
    category: "MiniRedone Series",
    images: ["/images/miniredone-iv.webp", "/images/miniredone-iv-1.webp", "/images/miniredone-iv-2.webp", "/images/miniredone-iv-3.webp"],
    colorVariant: false,
  },
  {
    slug: "miniredone-v",
    name: "MiniRedone-V",
    fullName: "MiniElephant MiniRedone-V",
    tagline: "Wide-body extra comfort : 900mm width for spacious seating",
    description:
      "The MiniRedone-V is the extra-wide premium electric wheelchair for users who demand generous space and uncompromising comfort. Because its expansive 900mm seat provides true first-class roominess, it delivers an exceptionally comfortable experience for larger users and anyone who values personal space — without the industrial feel of conventional wide wheelchairs. The reinforced one-piece magnesium alloy die-cast frame provides a stable, refined ride, and the premium dual 350W hub motors operate with whisper-quiet precision. Finished with high-grade materials and a 16Ah LiFePO₄ battery, the MiniRedone-V is the choice of customers who prioritize comfort, dignity, and quality in their mobility solution.",
    b2bPrice: "1990.00",
    specs: [
      { label: "Net Weight", value: "50 KG" },
      { label: "Max Load", value: "150 KG" },
      { label: "Range", value: "≈30 KM" },
      { label: "Max Speed", value: "≤6 KM/H" },
      { label: "Battery", value: "16Ah LiFePO₄ Lithium Battery" },
      { label: "Motor", value: "Dual 350W Self-developed Hub Motors" },
      { label: "Frame Material", value: "Magnesium Alloy (one-piece die-cast)" },
      { label: "Folded Dimensions", value: "L830×W900×H1200 mm" },
      { label: "Seat Dimensions", value: "L1005×W900×H1200 mm" },
      { label: "Seat Width", value: "Extra wide (900mm)" },
      { label: "Charging Time", value: "4-6 hours" },
    ],
    features: [
      "Extra wide 900mm seat : most spacious model",
      "50KG robust frame with reinforced construction",
      "Tall 1200mm backrest for full support",
      "One-piece magnesium alloy die-cast frame — wide-base stability",
      "Dual 350W self-developed hub motors : quiet brushless operation",
      "Manual maneuvering support is available when configured.",
      "16Ah LiFePO₄ battery",
      "Modular seat system compatible with multiple seat styles",
      "Pneumatic shock-absorbing front fork with gas spring",
      "Hand/foot dual brake system",
      "Wide anti-tip wheels for enhanced stability",
      "Anti-tip wheels for added stability",
    ],
    keyDifference: "Wide/extra comfort (W900mm seat)",
    category: "MiniRedone Series",
    images: ["/images/miniredone-v.webp", "/images/miniredone-v-1.webp", "/images/miniredone-v-2.webp", "/images/miniredone-v-3.webp"],
    colorVariant: false,
  },
];

export const allProducts = [...wheelchairs];

export function getProductBySlug(slug) {
  return allProducts.find((p) => p.slug === slug) || null;
}
